### ISSUE TITLE
Systemd services fail to start

### ISSUE THREAD

**Issue by arielm-cloudbuzz** [Locietta/xanmod-kernel-WSL2#36] opened 2023-04-18 20:13 UTC
![image](https://user-images.githubusercontent.com/110726427/232894869-51e9cf33-2480-4df5-9296-f285f8d607c3.png)

**Comment by Locietta** [comment] 2023-04-19 05:04
It's an upstream WSL issue, see microsoft/WSL#8853 for more info.

Not sure why cron.service is failing though, I was unable to reproduce it on my end.

I'm closing this issue now, if you can confirm it's due to this kernel, feel free to reopen and provide more details🙂

**Closed by Locietta** 2023-04-19 05:04 UTC
Labels: upstream
